name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: jchash test ${{ matrix.otp }} / rebar3 ${{ matrix.rebar3 }}
    strategy:
      matrix:
        otp: ['26.0', '25.3', '24.3']
        rebar3: ['3.22.0']
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - run: rebar3 eunit
