name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: jchash test ${{ matrix.otp }}
    strategy:
      matrix:
        otp: [26.0, 25.3, 24.2, 23.2]
    steps:
      - uses: actions/checkout@v2
      - uses: gleam-lang/setup-erlang@v1.1.3
        with:
          otp-version: ${{ matrix.otp }}
      - run: rebar3 eunit
